services:
  db-master:
    image: bitnami/mariadb-galera:latest
    container_name: db-master
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    env_file:
      - .env
    environment:
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
    volumes:
      - db_master_data:/bitnami/mariadb
    ports:
      - "3306:3306"
    networks:
      - wpnet

  db-slave:
    image: bitnami/mariadb-galera:latest
    container_name: db-slave
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    env_file:
      - .env
    environment:
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db-master
    volumes:
      - db_slave_data:/bitnami/mariadb
    ports:
      - "3307:3306"
    networks:
      - wpnet

  wordpress:
    image: wordpress:6.7
    depends_on:
      - db-master
      - db-slave
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - wpnet

volumes:
  db_master_data:
  db_slave_data:

networks:
  wpnet: